apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-hello-world-app
  template:
    metadata:
      labels:
        app: go-web-hello-world-app
    spec:
      containers:
      - name: go-web-hello-world-app
        image: dockram/go-web-hello-world:v0.2
        ports:
        - containerPort: 31080
apiVersion: v1
kind: Service                   
metadata:
  name: go-web-hello-world-app-service  
spec:
  type: NodePort                
  ports:                     
  - name: http
    port: 31080
    targetPort: 31080
  selector:
    app: go-web-hello-world-app
